AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation Sample Template VPC_with_PublicIPs_And_DNS: Sample template
  that creates a VPC with DNS and public IPs enabled. Note that you are billed
  for the AWS resources that you use when you create a stack from this template.
Parameters:
  bucketStack:
    Description: The name of the bucket stack
    Type: String
    MinLength: 1
    MaxLength: 255
  networkStack:
    Description: The name of the network stack
    Type: String
    MinLength: 1
    MaxLength: 255

Resources:
  cloudTrailRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": "s3.amazonaws.com"
              },
              "Action": "sts:AssumeRole"
            },
            {
              "Effect": "Allow",
              "Principal": {
                "Service": "cloudtrail.amazonaws.com"
              },
              "Action": "sts:AssumeRole"
            }
          ]
        }
      Description: the policy that is required for cloudtrail to send logs to an s3 bucket
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/CloudWatchLogsFullAccess"
        - "arn:aws:iam::aws:policy/AWSCloudTrailReadOnlyAccess"
      RoleName: cloudTrailLogRole
  cloudTrailLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: cloudTrailLogGroup
  flowLogMonitoring:
    Type: AWS::EC2::FlowLog
    Properties:
      LogDestination: !ImportValue
        'Fn::Sub':
          'Fn::Transform':
            - Name: 'String'
              Parameters:
                InputString: !Sub
                  - '${bucketStack}-bucketArn'
                  - {bearNetworkStack: !Ref bucketStack}
                Operation: Replace
                Old: "/"
                New: ""
      LogDestinationType: s3
      ResourceId: !ImportValue
        'Fn::Sub':
          'Fn::Transform':
            - Name: 'String'
              Parameters:
                InputString: !Sub
                  - '${networkStack}-PortalSubnetID'
                  - {bearNetworkStack: !Ref networkStack}
                Operation: Replace
                Old: "/"
                New: ""
      ResourceType: Subnet
      TrafficType: ALL

  cloudTrail:
    Type: AWS::CloudTrail::Trail
    Properties:
      CloudWatchLogsLogGroupArn: !GetAtt
        - cloudTrailLogGroup
        - Arn
      CloudWatchLogsRoleArn: !GetAtt
        - cloudTrailRole
        - Arn
      IsLogging: true
      S3BucketName: !ImportValue
        'Fn::Sub':
          'Fn::Transform':
            - Name: 'String'
              Parameters:
                InputString: !Sub
                  - '${bucketStack}-bucketLocation'
                  - {bearNetworkStack: !Ref bucketStack}
                Operation: Replace
                Old: "/"
                New: ""
      Tags:
        - Key: yuh
          Value: yuhyuh
      TrailName: bearCogCloudTrail
