AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation Sample Template VPC_with_PublicIPs_And_DNS: Sample template
  that creates a VPC with DNS and public IPs enabled. Note that you are billed
  for the AWS resources that you use when you create a stack from this template.

Resources:
  cloudTrailMonitoring:
    Type: AWS::EC2::FlowLog
    Properties:
      #DeliverLogsPermissionArn: String
      LogDestination: String
      LogDestinationType: String
      LogFormat: String
      LogGroupName: String
      MaxAggregationInterval: Integer
      ResourceId: String
      ResourceType: String
      Tags:
        - Tag
      TrafficType: String