AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation Sample Template VPC_with_PublicIPs_And_DNS: Sample template
  that creates a VPC with DNS and public IPs enabled. Note that you are billed
  for the AWS resources that you use when you create a stack from this template.
Parameters:
  networkStackName: #passes the networkStack Id
    Description: the bear network stacked that will be used to import necessary variables
    Type: String
    MinLength: 1
    MaxLength: 255
    Default: "bearNetworkStack"
  amiSelection: #This is used for a designated ami a client wishes to use
    Description: the ami that will be used
    Type: String
    Default: 'ami-09e67e426f25ce0d7'

Resources:
  ServerBear: #This creates an ec2 instance 
    Type: AWS::EC2::Instance
    Properties:
      AdditionalInfo: practice ec2
      AvailabilityZone: !ImportValue
        'Fn::Sub':
          'Fn::Transform':
            - Name: 'String'
              Parameters:
                InputString: !Sub
                  - '${bearNetworkStack}-PortalTableauSubnetAZ'
                  - {bearNetworkStack: !Ref networkStackName}
                Operation: Replace
                Old: "/"
                New: ""
      DisableApiTermination: False
      IamInstanceProfile: cloudWatchAgentUser
      ImageId: 'ami-08e08d7ff2687cede'
      InstanceType: t2.micro
      KeyName: practiceVolumeExperiment
      SecurityGroupIds:
        - !ImportValue
          'Fn::Sub':
            'Fn::Transform':
              - Name: 'String'
                Parameters:
                  InputString: !Sub
                    - '${bearNetworkStack}-TableauSecurityGroupID'
                    - {bearNetworkStack: !Ref networkStackName}
                  Operation: Replace
                  Old: "/"
                  New: ""

      SubnetId: !ImportValue
        'Fn::Sub':
          'Fn::Transform':
            - Name: 'String'
              Parameters:
                InputString: !Sub
                  - '${bearNetworkStack}-PortalTableauSubnetID'
                  - {bearNetworkStack: !Ref networkStackName}
                Operation: Replace
                Old: "/"
                New: ""

  serverNoVolAttatchEIP: #creates a server elastic ip to allow connection to the internet
    Type: AWS::EC2::EIP
    Properties:
      Domain: standard
      InstanceId: !Ref ServerBear