AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation Sample Template VPC_with_PublicIPs_And_DNS: Sample template
  that creates a VPC with DNS and public IPs enabled. Note that you are billed
  for the AWS resources that you use when you create a stack from this template.

Parameters:
  bucketStackName:
    Description: this will be the name of the bucket
    Type: String
    MinLength: 1
    MaxLength: 45
    AllowedPattern: "[a-z-]+"

Resources:
  bearNetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://bearcog-github-code.s3.amazonaws.com/perceptivity/bear_network_stack.yaml
  

  bearAppStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: bearMonitorStack
    Properties:
      TemplateURL: https://bearcog-github-code.s3.amazonaws.com/perceptivity/bear_app_stack.yaml
      Parameters:
        networkStackName:
          'Fn::Transform':
            - Name: 'String'
              Parameters:
                InputString: !GetAtt bearNetworkStack.StackId
                Operation: Replace
                Old: "/"
                New: ""

 

  bearBucketStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: bearNetworkStack
    Properties:
      TemplateURL: https://bearcog-github-code.s3.amazonaws.com/perceptivity/s3_bucket_stack.yaml
      Parameters:
        bucketName: !Ref bucketStackName
        allPrivateAccess: true

 

  bearMonitorStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: bearBucketStack
    Properties:
      TemplateURL: https://bearcog-github-code.s3.amazonaws.com/perceptivity/bear_monitor_stack.yaml
      Parameters:
        bucketStack:
          'Fn::Transform':
            - Name: 'String'
              Parameters:
                InputString: !Import
                  !Sub ''
                Operation: Replace
                Old: "/"
                New: ""
          #'Fn::Transform':
            #- Name: 'String'
              #Parameters:
                #InputString: !Sub '${!Ref bearBucketStack}'
                #Operation: Upper

        networkStack:
          'Fn::Transform':
            - Name: 'String'
              Parameters:
                InputString: !GetAtt bearNetworkStack.StackId
                Operation: Replace
                Old: "/"
                New: ""