AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation Sample Template VPC_with_PublicIPs_And_DNS: Sample template
  that creates a VPC with DNS and public IPs enabled. Note that you are billed
  for the AWS resources that you use when you create a stack from this template.
Parameters:
  networkStackName:
    Description: the bear network stacked that will be used to import necessary variables
    Type: String
    MinLength: 1
    MaxLength: 255
    #AllowedPattern: "^[a-zA-Z][-azA-Z0-9]*$"
    Default: "bearNetworkStack"
  #storedVolumeName:
    #Type: String
    #MinLength: 0
    #MaxLength: 255
    #AllowedPattern: "^[a-zA-Z][-azA-Z0-9]*$"
    #Default: ""
  #storedVolumeID:
    #Type: String
    #MinLength: 1
    #MaxLength: 255
    #AllowedPattern: "^[a-zA-Z][-azA-Z0-9]*$"
    #Default:
Resources:
  TableauServer:
    Type: AWS::EC2::Instance
    Properties:
      AdditionalInfo: practice ec2
      #Affinity: String
      AvailabilityZone: !ImportValue
        'Fn::Sub': '${networkStackName}-PortalTableauSubnetAZ'
      #BlockDeviceMappings:
        #- BlockDeviceMapping
      #CpuOptions:
        #CoreCount: 1 #ref server
        #ThreadsPerCore: 1 #ref server
      #CreditSpecification:
        #CreditSpecification
      DisableApiTermination: True
      #EbsOptimized: Boolean
      #ElasticGpuSpecifications:
        #- ElasticGpuSpecification
      #ElasticInferenceAccelerators:
        #- ElasticInferenceAccelerator
      #EnclaveOptions:
        #EnclaveOptions
      #HibernationOptions: This is interesting
        #HibernationOptions
      #HostId: String
      #HostResourceGroupArn: String
      IamInstanceProfile: cloudWatchAgentUser
      ImageId: 'ami-09e67e426f25ce0d7'
      #InstanceInitiatedShutdownBehavior: String
      InstanceType: t2.micro
      #Ipv6AddressCount: Integer
      #Ipv6Addresses:
        #- InstanceIpv6Address
      #KernelId: String
      KeyName: practiceVolumeExperiment
      #LaunchTemplate:
        #LaunchTemplateSpecification
      #LicenseSpecifications:
        #- LicenseSpecification
      #Monitoring: Boolean
      #NetworkInterfaces: !ImportValue
        #'Fn::Sub': '${networkStackName}-VPCID'
      #PlacementGroupName: String
      #PrivateIpAddress: String
      #RamdiskId: String
      SecurityGroupIds:
        - !ImportValue
          'Fn::Sub': '${networkStackName}-TableauSecurityGroupID'
      #SecurityGroups:
        #- String
      #SourceDestCheck: Boolean
      #SsmAssociations:
        #- SsmAssociation
      SubnetId: !ImportValue
        'Fn::Sub': '${networkStackName}-PortalSubnetID'
      #Tenancy: String
      #UserData: String to do later
      Volumes:
        - Device: /dev/sda1
          VolumeId: 'vol-06a8613acf18f186b'