---
AWSTemplateFormatVersion: 2010-09-09
Description: "AWS CloudFormation Sample Template VPC_with_PublicIPs_And_DNS: Sample template that creates a VPC with DNS and public IPs enabled. Note that you are billed for the AWS resources that you use when you create a stack from this template."
Outputs:
  Alb1Subnet:
    Description: "The subnet ID to use for public web servers"
    Export:
      Name: "${AWS::StackName}-Alb1SubnetID"
    Value: Alb1Subnet
  Alb2Subnet:
    Description: "The subnet ID to use for public web servers"
    Export:
      Name: "${AWS::StackName}-Alb2SubnetID"
    Value: Alb2Subnet
  PortalSecurityGroup:
    Description: "The security group ID to use for public web servers"
    Export:
      Name: "${AWS::StackName}-PortalSecurityGroupID"
    Value:
      - PortalSecurityGroup
      - GroupId
  PortalTableauSubnet:
    Description: "The subnet ID to use for public web servers"
    Export:
      Name: "${AWS::StackName}-PortalSubnetID"
    Value: PortalTableauSubnet
  TableauSecurityGroup:
    Description: "The security group ID to use for public web servers"
    Export:
      Name: "${AWS::StackName}-TableauSecurityGroupID"
    Value:
      - TableauSecurityGroup
      - GroupId
  VPCId:
    Description: "VPC ID"
    Export:
      Name: "${AWS::StackName}-VPCID"
    Value: BearVPC
Resources:
  Alb1Subnet:
    Properties:
      AvailabilityZone: us-east-1d
      CidrBlock: 172.31.32.0/20
      Tags:
        -
          Key: subnetName
          Value: applicationLoadBalancer1
      VpcId: BearVPC
    Type: "AWS::EC2::Subnet"
  Alb1SubnetNetworkAclAssociation:
    Properties:
      NetworkAclId:
        - BearVPC
        - DefaultNetworkAcl
      SubnetId: Alb1Subnet
    Type: "AWS::EC2::SubnetNetworkAclAssociation"
  Alb1SubnetRouteTableAssociation:
    Properties:
      RouteTableId: BearVPCRoutes
      SubnetId: Alb1Subnet
    Type: "AWS::EC2::SubnetRouteTableAssociation"
  Alb2Subnet:
    Properties:
      AvailabilityZone: us-east-1e
      CidrBlock: 172.31.48.0/20
      Tags:
        -
          Key: subnetName
          Value: applicationLoadBalancer2
      VpcId: BearVPC
    Type: "AWS::EC2::Subnet"
  Alb2SubnetNetworkAclAssociation:
    Properties:
      NetworkAclId:
        - BearVPC
        - DefaultNetworkAcl
      SubnetId: Alb2Subnet
    Type: "AWS::EC2::SubnetNetworkAclAssociation"
  Alb2SubnetRouteTableAssociation:
    Properties:
      RouteTableId: BearVPCRoutes
      SubnetId: Alb2Subnet
    Type: "AWS::EC2::SubnetRouteTableAssociation"
  BearVPC:
    Properties:
      CidrBlock: 172.31.0.0/16
      EnableDnsHostnames: "true"
      EnableDnsSupport: "true"
      Tags:
        -
          Key: vpcName
          Value: BearVPC
    Type: "AWS::EC2::VPC"
  BearVPCGatewayAttachment:
    Properties:
      InternetGatewayId: BearVPCIG
      VpcId: BearVPC
    Type: "AWS::EC2::VPCGatewayAttachment"
  BearVPCIG:
    Tags:
      -
        Key: vpcIGName
        Value: bearVPCIG
    Type: "AWS::EC2::InternetGateway"
  BearVPCRoutes:
    Properties:
      Tags:
        -
          Key: routeTableNames
          Value: vpcRoutes
      VpcId: BearVPC
    Type: "AWS::EC2::RouteTable"
  PortalSecurityGroup:
    Properties:
      GroupDescription: "Enable HTTP ingress"
      GroupName: PortalServer
      SecurityGroupIngress:
        -
          CidrIp: 174.56.158.129/32
          Description: "RDP from Bear Cognition Office"
          FromPort: "3389"
          IpProtocol: TCP
          ToPort: "3389"
        -
          CidrIp: 71.70.216.74/32
          Description: "TSM for Shannon"
          FromPort: "8850"
          IpProtocol: TCP
          ToPort: "8850"
        -
          CidrIp: 0.0.0.0/0
          Description: "port 80 from public"
          FromPort: "80"
          IpProtocol: TCP
          ToPort: "80"
        -
          CidrIp: 75.35.119.139/32
          Description: "Teknion - Antony Remote"
          FromPort: "3389"
          IpProtocol: TCP
          ToPort: "3389"
        -
          CidrIp: 216.215.101.210/32
          Description: "Teknion Office"
          FromPort: "3389"
          IpProtocol: TCP
          ToPort: "3389"
        -
          CidrIp: 207.98.168.34/32
          Description: "RDP from Kayce Remote"
          FromPort: "3389"
          IpProtocol: TCP
          ToPort: "3389"
        -
          CidrIp: 18.214.79.188/32
          Description: "SQL Server from Tableau Server"
          FromPort: "1433"
          IpProtocol: TCP
          ToPort: "1433"
        -
          CidrIp: 172.31.24.73/32
          Description: "SQL Server from Tableau internal"
          FromPort: "1433"
          IpProtocol: TCP
          ToPort: "1433"
        -
          CidrIp: 174.56.158.129/32
          Description: "SQL Server from Bear Cognition Office"
          FromPort: "1433"
          IpProtocol: TCP
          ToPort: "1433"
        -
          CidrIp: 0.0.0.0/0
          Description: "port 443 from public"
          FromPort: "443"
          IpProtocol: TCP
          ToPort: "443"
        -
          CidrIp: 69.73.96.41/32
          Description: "SQL for Ben Remote"
          FromPort: "1433"
          IpProtocol: TCP
          ToPort: "1433"
        -
          CidrIp: 207.98.168.34/32
          Description: "SQL from Kayce Remote"
          FromPort: "1433"
          IpProtocol: TCP
          ToPort: "1433"
      Tags:
        -
          Key: sgName
          Value: portalSecurityGroup
      VpcId: BearVPC
    Type: "AWS::EC2::SecurityGroup"
  PortalTableauSubnet:
    Properties:
      AvailabilityZone: us-east-1c
      CidrBlock: 172.31.16.0/20
      Tags:
        -
          Key: subnetName
          Value: portalTableauSubnet
      VpcId: BearVPC
    Type: "AWS::EC2::Subnet"
  PortalTableauSubnetNetworkAclAssociation:
    Properties:
      NetworkAclId:
        - BearVPC
        - DefaultNetworkAcl
      SubnetId: PortalTableauSubnet
    Type: "AWS::EC2::SubnetNetworkAclAssociation"
  PortalTableauSubnetRouteTableAssociation:
    Properties:
      RouteTableId: BearVPCRoutes
      SubnetId: PortalTableauSubnet
    Type: "AWS::EC2::SubnetRouteTableAssociation"
  PublicRoute:
    DependsOn: BearVPCGatewayAttachment
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: BearVPCIG
      RouteTableId: BearVPCRoutes
    Type: "AWS::EC2::Route"
  TableauSecurityGroup:
    Properties:
      GroupDescription: "Enable HTTP ingress"
      GroupName: TableauServer
      SecurityGroupIngress:
        -
          CidrIp: 174.56.158.129/32
          Description: "tcp ssh bear cognition office"
          FromPort: "22"
          IpProtocol: tcp
          ToPort: "22"
        -
          CidrIp: 207.98.168.34/32
          Description: "TSM Kayce Remote"
          FromPort: "8850"
          IpProtocol: tcp
          ToPort: "8850"
        -
          CidrIp: 192.195.4.33/32
          Description: "SSH from Tableau office"
          FromPort: "22"
          IpProtocol: tcp
          ToPort: "22"
        -
          CidrIp: 174.56.158.129/32
          Description: "Backup Port when upgrading ubuntu"
          FromPort: "1022"
          IpProtocol: tcp
          ToPort: "1022"
        -
          CidrIp: 52.71.170.75/32
          Description: "HTTP from portal server"
          FromPort: "80"
          IpProtocol: tcp
          ToPort: "80"
        -
          CidrIp: 0.0.0.0/0
          Description: "HTTPS from portal server"
          FromPort: "443"
          IpProtocol: tcp
          ToPort: "443"
        -
          CidrIp: 207.98.168.34/32
          Description: "SSH Kayce Remote"
          FromPort: "22"
          IpProtocol: tcp
          ToPort: "22"
        -
          CidrIp: 192.195.4.33/32
          Description: "TSM from Tableau office"
          FromPort: "8850"
          IpProtocol: tcp
          ToPort: "8850"
        -
          CidrIp: 174.56.158.129/32
          Description: "Postgres Bear Cognition Office"
          FromPort: "8060"
          IpProtocol: tcp
          ToPort: "8060"
        -
          CidrIp: 172.31.27.228/32
          Description: "HTTP from internal portal IP"
          FromPort: "80"
          IpProtocol: tcp
          ToPort: "80"
        -
          CidrIp: 207.98.168.34/32
          Description: "HTTP Kayce Remote"
          FromPort: "80"
          IpProtocol: tcp
          ToPort: "80"
        -
          CidrIp: 174.56.158.129/32
          Description: "SMB share Bear Cognition Office"
          FromPort: "445"
          IpProtocol: tcp
          ToPort: "445"
        -
          CidrIp: 174.56.158.129/32
          Description: "HTTPS Bear Cognition Office"
          FromPort: "443"
          IpProtocol: tcp
          ToPort: "443"
        -
          CidrIp: 174.56.158.129/32
          Description: "HTTP Bear Cognition Office"
          FromPort: "80"
          IpProtocol: tcp
          ToPort: "80"
        -
          CidrIp: 207.98.168.34/32
          Description: "Postgres Kayce Remote"
          FromPort: "8060"
          IpProtocol: tcp
          ToPort: "8060"
        -
          CidrIp: 71.70.216.74/32
          Description: "TSM Shonnon CBH"
          FromPort: "8850"
          IpProtocol: tcp
          ToPort: "8850"
        -
          CidrIp: 174.56.158.129/32
          Description: "TSM Bear Cognition Office"
          FromPort: "8850"
          IpProtocol: tcp
          ToPort: "8850"
      Tags:
        -
          Key: sgName
          Value: tableauSecurityGroup
      VpcId: BearVPC
    Type: "AWS::EC2::SecurityGroup"
