AWSTemplateFormatVersion: 2010-09-09 #This section of the template will always have the same value
Description: >-
  This is a template that will be used as a nested stack of S3 buckets.
Parameters:
  bucketName: #parameters are values passed for the rest of the template to use later on in this case we are passing the bucket name
    Description: this will be the name of the bucket
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: "[a-z-]+"
  allPrivateAccess: #this determines whether a bucket will
    Description: a boolean that states whether your bucket is public or private
    Type: String
    AllowedValues: [True, False]
Resources:
  myS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Ref bucketName
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      PublicAccessBlockConfiguration:
        BlockPublicAcls: !Ref allPrivateAccess
        BlockPublicPolicy: !Ref allPrivateAccess
        IgnorePublicAcls: !Ref allPrivateAccess
        RestrictPublicBuckets: !Ref allPrivateAccess
      Tags:
        - Key: bucketName
          Value: !Ref bucketName

  cloudTrailBucketPolicy:

    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref myS3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: '1'
            Effect: Allow
            Principal:
              Service: logs.us-east-1.amazonaws.com
            Action: 's3:GetBucketAcl'
            Resource: !GetAtt
              - myS3Bucket
              - Arn
          - Sid: '2'
            Effect: Allow
            Principal:
              Service: logs.us-east-1.amazonaws.com
            Action: 's3:PutObject'
            Resource: !Join
              - ""
              - - !GetAtt
                  - myS3Bucket
                  - Arn
                - "/*"
            Condition:
              StringEquals:
                's3:x-amz-acl': bucket-owner-full-control
          - Sid: AWSLogDeliveryWrite
            Effect: Allow
            Principal:
              Service: delivery.logs.amazonaws.com
            Action: 's3:PutObject'
            Resource: !Join
              - ""
              - - !GetAtt
                  - myS3Bucket
                  - Arn
                - "/*"
            Condition:
              StringEquals:
                's3:x-amz-acl': bucket-owner-full-control
          - Sid: AWSLogDeliveryAclCheck
            Effect: Allow
            Principal:
              Service: delivery.logs.amazonaws.com
            Action: 's3:GetBucketAcl'
            Resource: !GetAtt
              - myS3Bucket
              - Arn
          - Sid: AWSCloudTrailAclCheck20150319
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: 's3:GetBucketAcl'
            Resource: !GetAtt
              - myS3Bucket
              - Arn
          - Sid: AWSCloudTrailWrite20150319
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: 's3:PutObject'
            Resource: !Join
              - ""
              - - !GetAtt
                  - myS3Bucket
                  - Arn
                - "/*"
            Condition:
              StringEquals:
                's3:x-amz-acl': bucket-owner-full-control

Outputs:
  bucketLocation:
    Description: the name of the S3 bucket for reference
    Value: !Ref myS3Bucket
    Export:
      Name:
        'Fn::Transform':
          - Name: 'String'
            Parameters:
              InputString: !Sub '${AWS::StackId}-bucketLocation'
              Operation: Replace
              Old: "/"
              New: ""

  bucketArn:
    Description: the ARN of the s3 bucket
    Value: !Join
      - ''
      - - !GetAtt
          - myS3Bucket
          - Arn
        - "/"
    Export:
      Name:
        'Fn::Transform':
          - Name: 'String'
            Parameters:
              InputString: !Sub '${AWS::StackId}-bucketArn'
              Operation: Replace
              Old: "/"
              New: ""